import { 
  Brain, 
  Megaphone, 
  Code2, 
  CreditCard, 
  ShieldCheck, 
  Network, 
  Users, 
  Database, 
  PenTool, 
  Headset, 
  CloudCog, 
  LineChart,
  Sparkles,
  Terminal,
  Activity,
  Layers,
  Palette,
  MessageSquare,
  Mic,
  Lock
} from 'lucide-react';

export const CATEGORIES = [
  { name: 'AI', icon: Brain },
  { name: 'Marketing', icon: Megaphone },
  { name: 'Development', icon: Code2 },
  { name: 'Fintech', icon: CreditCard },
  { name: 'Security', icon: ShieldCheck },
  { name: 'Web3', icon: Network },
  { name: 'HR & Ops', icon: Users },
  { name: 'Data', icon: Database },
  { name: 'Design', icon: PenTool },
  { name: 'Support', icon: Headset },
  { name: 'DevOps', icon: CloudCog },
  { name: 'Analytics', icon: LineChart },
];

export const SPONSORED_TOOLS = [
  {
    id: 's1',
    name: 'Nexus Flow',
    description: 'Automate complex multi-step workflows with our intuitive AI agent engine.',
    logo: 'https://picsum.photos/seed/nexus/100/100',
  },
  {
    id: 's2',
    name: 'Quartz Analytics',
    description: 'Real-time user behavior analytics for high-growth SaaS applications.',
    logo: 'https://picsum.photos/seed/quartz/100/100',
  },
  {
    id: 's3',
    name: 'Vantage CRM',
    description: 'The only sales pipeline management tool built specifically for remote teams.',
    logo: 'https://picsum.photos/seed/vantage/100/100',
  },
];

export const TOOLS = [
  {
    id: 't1',
    name: 'Luminal AI',
    description: 'The fastest way to generate professional landing pages from simple text prompts.',
    icon: Sparkles,
    tags: ['AI', 'Design'],
    rating: 4.9,
    upvotes: 142,
    verified: true,
    pricing: 'Freemium',
    logo: 'https://picsum.photos/seed/luminal/100/100',
    logoBg: 'bg-zinc-900',
    logoColor: 'text-white'
  },
  {
    id: 't2',
    name: 'CodeFlow',
    description: 'Visual debugger for TypeScript and Rust environments with real-time stack monitoring.',
    icon: Terminal,
    tags: ['DevTools', 'Free'],
    rating: 4.7,
    upvotes: 89,
    verified: false,
    pricing: 'Free',
    logo: 'https://picsum.photos/seed/codeflow/100/100',
    logoBg: 'bg-zinc-100',
    logoColor: 'text-zinc-900'
  },
  {
    id: 't3',
    name: 'Metricly',
    description: 'Advanced analytics for subscription-based businesses. Track MRR, churn, and LTV automatically.',
    icon: Activity,
    tags: ['Business', 'SaaS'],
    rating: 5.0,
    upvotes: 256,
    verified: true,
    pricing: 'Paid',
    logo: 'https://picsum.photos/seed/metricly/100/100',
    logoBg: 'bg-zinc-800',
    logoColor: 'text-white'
  },
  {
    id: 't4',
    name: 'StackBuilder',
    description: 'Plan your infrastructure stack and estimate monthly costs before writing a single line of code.',
    icon: Layers,
    tags: ['Infrastructure'],
    rating: 4.4,
    upvotes: 120,
    verified: false,
    pricing: 'Free',
    logo: 'https://picsum.photos/seed/stackbuilder/100/100',
    logoBg: 'bg-zinc-200',
    logoColor: 'text-zinc-900'
  },
  {
    id: 't5',
    name: 'EditorX',
    description: 'A professional web design tool that combines drag-and-drop with advanced layout capabilities.',
    icon: Palette,
    tags: ['No-Code', 'Design'],
    rating: 4.8,
    upvotes: 312,
    verified: true,
    pricing: 'Paid',
    logo: 'https://picsum.photos/seed/editorx/100/100',
    logoBg: 'bg-zinc-950',
    logoColor: 'text-white'
  },
  {
    id: 't6',
    name: 'BuzzWire',
    description: 'Automated social media distribution for early-stage startups and indie hackers.',
    icon: Megaphone,
    tags: ['Marketing'],
    rating: 4.2,
    upvotes: 54,
    verified: false,
    pricing: 'Freemium',
    logo: 'https://picsum.photos/seed/buzzwire/100/100',
    logoBg: 'bg-zinc-400',
    logoColor: 'text-zinc-900'
  },
  {
    id: 't7',
    name: 'WhatsFly',
    description: 'WhatsFly centralizes WhatsApp, Facebook, Instagram and more into one platform.',
    icon: MessageSquare,
    tags: ['CRM', 'Marketing'],
    rating: 0.0,
    upvotes: 1,
    verified: true,
    pricing: 'From $20/mo',
    logo: 'https://picsum.photos/seed/whatsfly/100/100',
    logoBg: 'bg-indigo-50',
    logoColor: 'text-indigo-600'
  },
  {
    id: 't8',
    name: 'Symphony',
    description: 'High-fidelity voice synthesis for modern content creators.',
    icon: Mic,
    tags: ['Audio'],
    rating: 0.0,
    upvotes: 156,
    verified: false,
    pricing: 'Free Trial',
    logo: 'https://picsum.photos/seed/symphony/100/100',
    logoBg: 'bg-orange-50',
    logoColor: 'text-orange-600'
  },
  {
    id: 't9',
    name: 'SecureGrid',
    description: 'End-to-end encryption for modern cloud database migrations.',
    icon: Lock,
    tags: ['Security'],
    rating: 0.0,
    upvotes: 82,
    verified: false,
    pricing: 'From $120/mo',
    logo: 'https://picsum.photos/seed/securegrid/100/100',
    logoBg: 'bg-red-50',
    logoColor: 'text-red-600'
  }
];
